In [45]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [46]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/FYP_IIT/Predictions_Dataset.csv', encoding='latin1')
df.head()

,gender,academic_year,age_group,degree_program,home_environment,academic_failure,faculty_environment,F1,F2,F3,F4
0,Female,Year 4,22-23,B.B.A. (Hons) in Business Economics,Yes,Never,Satisfied,3.333333,4.000000,3.00,2.5
1,Female,Year 4,22-23,B.B.A. (Hons) in International Business,Yes,Never,Satisfied,3.000000,3.666667,2.75,2.0
2,Female,Year 4,22-23,B.B.A. (Hons) in Human Resource Management,Yes,Never,Very satisfied,3.500000,2.000000,2.00,2.0
3,Male,Year 4,22-23,B.B.A. (Hons) in Business Economics,Yes,Once or twice,Satisfied,3.000000,3.000000,2.50,3.0
4,Male,Year 4,22-23,B.B.A. (Hons) in Business Economics,Yes,Never,Satisfied,3.833333,4.333333,1.50,4.0

In [47]:
df['age_group'] = df['age_group'].replace(
    ['24-25', '26 and above'],
    '24 and above'
)

In [48]:
df['faculty_environment'] = df['faculty_environment'].astype(str).str.strip()

df['faculty_environment'] = df['faculty_environment'].replace({
    'Dissatisfied': 'Not satisfied',
    'Very dissatisfied': 'Not satisfied'
})

In [49]:
df['faculty_environment'].value_counts()

faculty_environment
Satisfied                             1135
Very satisfied                         283
Neither satisfied nor dissatisfied     271
Not satisfied                           74
Name: count, dtype: int64

In [50]:
df['degree_program'] = df['degree_program'].replace({
    'B.B.A. (Hons) in Business Administration': 'Other',
    'B.B.A. (Hons) in Hospitality and Leisure Management': 'Other',
    'B.B.A. (Hons) in Human Resource Management': 'Other'
})

In [51]:
df['degree_program'].value_counts()

degree_program
Other                                      195
B.B.A. (Hons) in Finance                   183
B.B.A. (Hons) in Marketing                 146
B.B.A. (Hons) in Business Economics        138
B.B.A. (Hons) in International Business    124
B.B.A. (Hons) in Accounting                119
Name: count, dtype: int64

In [52]:
# Remove extra spaces and ensure string format
df['degree_program'] = df['degree_program'].astype(str).str.strip()

# Replace empty strings with 'General'
df['degree_program'] = df['degree_program'].replace('', 'General')

# Replace actual NaN values with 'General'
df['degree_program'] = df['degree_program'].replace('nan', 'General')

In [53]:
df['degree_program'].value_counts()

degree_program
General                                    858
Other                                      195
B.B.A. (Hons) in Finance                   183
B.B.A. (Hons) in Marketing                 146
B.B.A. (Hons) in Business Economics        138
B.B.A. (Hons) in International Business    124
B.B.A. (Hons) in Accounting                119
Name: count, dtype: int64

In [54]:
df.dtypes

gender                  object
academic_year           object
age_group               object
degree_program          object
home_environment        object
academic_failure        object
faculty_environment     object
F1                     float64
F2                     float64
F3                     float64
F4                     float64
dtype: object

In [55]:
X = df[[
    'gender','academic_failure','faculty_environment',
    'home_environment','age_group','academic_year','degree_program'
]]

Y = df[['F1','F2','F3','F4']]

In [56]:
df_encoded = pd.get_dummies(df, drop_first=False)

In [57]:
X_encoded = df_encoded.drop(columns=['F1', 'F2', 'F3', 'F4'])
X_encoded.head()
Y.head()

         F1        F2    F3   F4
0  3.333333  4.000000  3.00  2.5
1  3.000000  3.666667  2.75  2.0
2  3.500000  2.000000  2.00  2.0
3  3.000000  3.000000  2.50  3.0
4  3.833333  4.333333  1.50  4.0

In [58]:
final_df = pd.concat([X_encoded, Y], axis=1)

final_df.head()

,gender_Female,gender_Male,academic_year_Year 1,academic_year_Year 2,academic_year_Year 3,academic_year_Year 4,age_group_20-21,age_group_22-23,age_group_24 and above,degree_program_B.B.A. (Hons) in Accounting,...,academic_failure_Once or twice,academic_failure_Three or more times,faculty_environment_Neither satisfied nor dissatisfied,faculty_environment_Not satisfied,faculty_environment_Satisfied,faculty_environment_Very satisfied,F1,F2,F3,F4
0,True,False,False,False,False,True,False,True,False,False,...,False,False,False,False,True,False,3.333333,4.000000,3.00,2.5
1,True,False,False,False,False,True,False,True,False,False,...,False,False,False,False,True,False,3.000000,3.666667,2.75,2.0
2,True,False,False,False,False,True,False,True,False,False,...,False,False,False,False,False,True,3.500000,2.000000,2.00,2.0
3,False,True,False,False,False,True,False,True,False,False,...,True,False,False,False,True,False,3.000000,3.000000,2.50,3.0
4,False,True,False,False,False,True,False,True,False,False,...,False,False,False,False,True,False,3.833333,4.333333,1.50,4.0

In [59]:
X_encoded = X_encoded.astype(int)

In [60]:
final_df = pd.concat([X_encoded, Y], axis=1)

final_df.head()

,gender_Female,gender_Male,academic_year_Year 1,academic_year_Year 2,academic_year_Year 3,academic_year_Year 4,age_group_20-21,age_group_22-23,age_group_24 and above,degree_program_B.B.A. (Hons) in Accounting,...,academic_failure_Once or twice,academic_failure_Three or more times,faculty_environment_Neither satisfied nor dissatisfied,faculty_environment_Not satisfied,faculty_environment_Satisfied,faculty_environment_Very satisfied,F1,F2,F3,F4
0,1,0,0,0,0,1,0,1,0,0,...,0,0,0,0,1,0,3.333333,4.000000,3.00,2.5
1,1,0,0,0,0,1,0,1,0,0,...,0,0,0,0,1,0,3.000000,3.666667,2.75,2.0
2,1,0,0,0,0,1,0,1,0,0,...,0,0,0,0,0,1,3.500000,2.000000,2.00,2.0
3,0,1,0,0,0,1,0,1,0,0,...,1,0,0,0,1,0,3.000000,3.000000,2.50,3.0
4,0,1,0,0,0,1,0,1,0,0,...,0,0,0,0,1,0,3.833333,4.333333,1.50,4.0

In [61]:
df_encoded.shape

(1763, 29)

In [62]:
df_encoded = df_encoded.apply(
    lambda x: x.astype(int) if x.dtype == 'bool' else x
)

In [64]:
# Save dataset to CSV
df_encoded.to_csv('Cleaned_Prediction_Dataset.csv', index=False)

# Download it
from google.colab import files
files.download('Cleaned_Prediction_Dataset.csv')